#!/usr/bin/env guile
!#

(load "spec.scm")

(use-modules 
  (language php parse)
  (language php tokenize))

(define (read file)
  (read-php (open-file file "r")))

(define (comp file)
  (compile (call-with-input-file file read-php) #:from 'php #:to 'value))

(define (tokenize file)
  (let ((lexer (make-tokenizer (open-file file "r"))))
    (let loop ((tok (lexer)))
      (display tok)
      (newline)
      (if (not (eq? tok '*eoi*))
        (loop (lexer))))))

;(tokenize "tests/test.php")
;(read "tests/test.php")

(comp "tests/test.php")
