#!/usr/bin/env guile
!#

;;; PHP for GNU Guile

;; Copyright (C) 2010 Jon Herron

;; This library is free software; you can redistribute it and/or
;; modify it under the terms of the GNU Lesser General Public
;; License as published by the Free Software Foundation; either
;; version 3 of the License, or (at your option) any later version.
;; 
;; This library is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; Lesser General Public License for more details.
;; 
;; You should have received a copy of the GNU Lesser General Public
;; License along with this library; if not, write to the Free Software
;; Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
;; 02110-1301 USA


(include "spec.scm")

(use-modules 
  (language php parse)
  (language php tokenize))

(define (read file)
  (read-php (open-file file "r")))

(define (comp file)
  (compile (call-with-input-file file read-php) #:from 'php #:to 'value))

(define (tokenize file)
  (let ((lexer (make-tokenizer (open-file file "r"))))
    (let loop ((tok (lexer)))
      (display tok)
      (newline)
      (if (not (eq? tok '*eoi*))
        (loop (lexer))))))

;(tokenize "tests/test.php")
;(read "tests/test.php")

(comp "tests/test.php")
