#!/usr/bin/env guile
!#

;;; PHP for GNU Guile

;; Copyright (C) 2010 Jon Herron

;; This library is free software; you can redistribute it and/or
;; modify it under the terms of the GNU Lesser General Public
;; License as published by the Free Software Foundation; either
;; version 3 of the License, or (at your option) any later version.
;; 
;; This library is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; Lesser General Public License for more details.
;; 
;; You should have received a copy of the GNU Lesser General Public
;; License along with this library; if not, write to the Free Software
;; Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
;; 02110-1301 USA


(include "silex.scm")
(use-modules (ice-9 rdelim))

(define (copy-port src-port dest-port)
  (let loop ((line (read-line src-port)))
    (if (eof-object? line)
      #t
      (begin
        (write-line line dest-port)
        (loop (read-line src-port))))))
        
;(copy-port src-port dest-port)))))

(define (merge-tokenizers)
  (let ((base-tokenizer (open-file "tokenize-base.scm" "r")) 
    (silex-tokenizer (open-file "tokenize-silex.scm" "r")) 
    (tokenizer (open-file "tokenize.scm" "w")))
    (copy-port base-tokenizer tokenizer)
    (copy-port silex-tokenizer tokenizer)
    (close-port base-tokenizer)
    (close-port silex-tokenizer)
    (close-port tokenizer)))

(lex "php.l" "tokenize-silex.scm")
(merge-tokenizers)
